### ISSUE TITLE
Is there any way to sync via a socks or http proxy?

### ISSUE THREAD

**Issue by troilus** [alex-donnan/SyncFTP#1]
Due to the network issue that I can not use ssh or sfpt directly, can I use the plugin via socks or http proxy?

**Comment by troilus** [comment]
Maybe I should edit the main.js?
https://www.npmjs.com/package/ssh2-sftp-client#org175d696

**Comment by alex-donnan** [comment]
I will look at adding the SOCKs proxy to the plugin, as this takes higher priority in terms of availability of use.

**Comment by alex-donnan** [comment]
Socks proxy added in 1.3.0

**Comment by troilus** [comment]
Have tried 1.3.0 and set a local host Socks5 proxy,  but seems unable to connect.
[obsidian.md-1686616385243.log](https://github.com/alex-donnan/SyncFTP/files/11729475/obsidian.md-1686616385243.log)

**Comment by alex-donnan** [comment]
Thanks for letting me know, I'll do some more testing and verify!

**Comment by alex-donnan** [comment]
Just released 1.3.1, tested w/ a public socks proxy and had success. Please let me know if you run into the same issue.

**Comment by troilus** [comment]
Works correctly in 1.3.1, thanks for the update!
