### ISSUE TITLE
How to get lost date back!?!

### ISSUE THREAD

**Issue by plisskien** [alex-donnan/SyncFTP#10]
So, idk why but this fucking shit synced without my consent, and I fucking downloaded outdated data from my server fucking my notes. 
Thus is there any way to get it back?, ngl I'm fucking very angry, ty for any help in advance.

**Comment by alex-donnan** [comment]
Unless the files were backed up anywhere else they are lost. Syncing is destructive. If the auto-sync function is turned off and the sync still occurred on load please let me know as it should default to disabled.

**Comment by plisskien** [comment]
EDIT, there is sth like file recovery in settings, ty for guy who created this shit <3 

I would call it ISSUE since you can lost ur files, so I request option that will check content from server and local content so user see what is happening, ty! Cuz of that shit I could have suicide attempt...

**Comment by plisskien** [comment]
> Unless the files were backed up anywhere else they are lost. Syncing is destructive. If the auto-sync function is turned off and the sync still occurred on load please let me know as it should default to disabled.

Ty for response, I don't think so that I'm first guy with this problem, true this feature should be turned off, I'll keep it in this way! Also ty for this cool project, ngl it is helping a lot, and also it is introducing new problems as well! 

⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣤⣤⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣿⣿⣿⣿⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣿⣿⣿⣿⣿⣿⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣿⣿⡿⠁⠈⢿⣿⣿⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⢀⣴⣿⣿⠟⠀⠀⠀⠀⠻⣿⣿⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⢀⣴⣿⣿⡿⠃⠀⠀⠀⠀⠀⠀⠘⢿⣿⣿⣦⡀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⣾⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣷⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⢹⣿⣿⣿⡄⠀⠀⠀⠀⠀⠀⠀⠀⢠⣿⣿⣿⡏⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠈⢿⣿⣿⣿⣦⡀⠀⠀⠀⠀⢀⣴⣿⣿⣿⡿⠁⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠙⠿⣿⣿⣿⣷⣶⣶⣾⣿⣿⣿⠿⠋⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠙⠛⠛⠛⠛⠋⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀

**Comment by alex-donnan** [comment]
Looking over Obsidian documentation, please check:
1. `Files and links - Deleted files` - Your files may be in your system trash
2. `File Recovery` - Your files may be captured in your Snapshots (defaulted to 5 minutes, 7 day retention)
