### ISSUE TITLE
[Feature Request]: Information in StatusBar

### ISSUE THREAD

**Issue by troilus** [alex-donnan/SyncFTP#2]
Likes [https://github.com/vrtmrz/obsidian-livesync](https://github.com/vrtmrz/obsidian-livesync) sync informationin StatusBar.

Status：
⏹️ Stopped
💤 SyncFTP is enabled. Waiting for changes.
⚡️ Synchronize is now in progress.
⚠ Error occurred.
↑ Uploaded pieces
↓ Downloaded pieces
⏳ Count of the pending process

**Comment by alex-donnan** [comment]
Thanks for the recommendation and pointing me to the livesync plugin as well. I do not have a strict timeline but will consider these.

**Comment by alex-donnan** [comment]
Further updates may happen but are not planned, as core functionality was my primary goal. Closing this now, further update consideration will be at my discretion.
