### ISSUE TITLE
Unable to enable the plugin on mobile(iOS).

### ISSUE THREAD

**Issue by troilus** [alex-donnan/SyncFTP#3]
![image](https://github.com/alex-donnan/SyncFTP/assets/1055100/a0c353b7-04ec-457c-9449-0bf02a9964f2)

**Comment by troilus** [comment]
I have edit the "isDesktopOnly" to false but still "Failed to load plugin SyncFTP.

**Comment by alex-donnan** [comment]
Unfortunately using the ssh2-sftp-client package does not allow this to work with mobile. I may look at other alternatives in the future, as I would like this to function on mobile as well.
