### ISSUE TITLE
How to install this plugin

### ISSUE THREAD

**Issue by vinhnghiemnguyen** [alex-donnan/SyncFTP#4]
I search in the Community Obsidian plugin page but did not find this plugin so I try to manually install this plugin. 
I copy the source to .obsidian/plugins folder but I don't know what to do with 2 dependencies (ssh2-sftp-client and sock), could you please give more details. 
Thanks

**Comment by alex-donnan** [comment]
Thanks for reaching out. Unfortunately, the Obsidian team has not yet added it to their official plugin releases despite approval.

For manual install, both dependencies are restricted to desktop and will fail if installed on mobile. From the [release page](https://github.com/alex-donnan/SyncFTP/releases/tag/1.3.1) you should only need main.js and manifest.json in a new folder called SyncFTP in the .obsidian/plugins/ folder. From there you can navigate to the Community Plugins tab, refresh, and enable.

**Comment by alex-donnan** [comment]
SyncFTP is available for download in Obsidian
