### ISSUE TITLE
Does it support SFTP?

### ISSUE THREAD

**Issue by gerroon** [alex-donnan/SyncFTP#9]
Hi

I have a running SSH server that supports SFTP. Would this work?

**Comment by alex-donnan** [comment]
Yep! Any formally supported SFTP server should be accessible.

**Comment by gerroon** [comment]
Thanks for the reply. It looks like there is not a way to provide  a key file for SFTP. Do you plan to support it?

**Comment by alex-donnan** [comment]
I initially hadn't but the base package that is used for the connection does provide key file functionality. I'll take a look at adding that, as that shouldn't be an issue to implement
